# Generated by Django 4.2.5 on 2023-09-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPreference', '0002_categories'),
        ('expenses', '0002_expense_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userPreference.categories'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
