# Generated by Django 4.2.5 on 2023-10-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPreference', '0004_alter_categories_user'),
        ('expenses', '0005_alter_expense_category_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPreference.categories'),
        ),
    ]
