# Generated by Django 4.2.5 on 2023-10-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPreference', '0004_alter_categories_user'),
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPreference.categories'),
        ),
    ]
